name: macOS Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # 允许手动触发

jobs:

  build-macos-arm64:
    runs-on: macos-latest
    name: Build for macOS arm64
    env:
      # 设置环境变量以确保脚本正确识别构建环境
      BUILD_ARCH: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project for arm64
      run: |
        # 确保脚本有执行权限
        chmod +x ./source/macos.sh
        # 执行构建脚本
        ./source/macos.sh

    - name: Upload artifact for arm64
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64
        path: ./lib/macos/arm64/PebView.dylib
        if-no-files-found: error